from manimlib.imports import *
from NumberCreature.NumberCreature import *

class kaitou(Scene):
    def construct(self):
        text1 = TextMobject("本视频开始前，先问大家一个","问题").to_edge(UP)
        text1[1].set_color(GREEN)
        Ale1 = Alex1().shift(DOWN).set_color(YELLOW)
        text2 = TextMobject("寒假作业写完没?").set_color(YELLOW)

        self.play(Write(text1))
        self.wait(0.5)
        self.play(Write(Ale1),run_time=0.8)
        self.play(NumberCreatureSays(
            Ale1, text2,
            bubble_kwargs={"height": 2, "width": 4},
            target_mode="speaking"
        ))
        self.wait(3)

class frist(Scene):
    def construct(self):
        text1 = TextMobject("正","片","开","始").scale(3)
        text1[0].set_color(YELLOW)
        text1[1].set_color(RED)
        text1[2].set_color(GREEN)
        text1[3].set_color(ORANGE)
        text2 = TextMobject("如何","~~~证明").shift(UP*2+LEFT*3)
        text2[1].scale(2).set_color(RED)
        text3 = TextMobject("寒假作业").set_color(BLUE_D).scale(3)
        text4= TextMobject("是","~~~永远~~~","~~~写不完的~~~","呢?").shift(DOWN*2+RIGHT*3)
        text4[1].set_color(YELLOW).scale(2)
        text4[2].set_color(GREEN).scale(1.5)
        text_a=VGroup(text2,text3,text4)
        text5 = TextMobject("证：").to_corner(UL).set_color(ORANGE)
        text6 = TextMobject("假设作业的总量为$x(x\\neq 0)$，$Q_{n}$表截止第$n$个阶段完成量").next_to(text5,RIGHT).scale(0.8)
        text8 = TextMobject("如果我们想要完成作业，则必须先写完","作业的一半").to_edge(UP,2)
        text8[1].set_color(GREEN)
        text9 = TextMobject("那么","第一阶段","就可以表示为").to_edge(UP,1.5)
        text9[1].set_color(BLUE_C)
        text10 = TexMobject(r"Q_{1}=\frac{x}{2}").set_color(YELLOW).next_to(text9,DOWN,1)
        text11 = TextMobject("同样的，如果我们想要完成","剩下的作业").to_edge(UP,1.5)
        text11[1].set_color(ORANGE)
        text12 = TextMobject("我们必须先写完","剩下作业的一半").to_edge(UP,1.5)
        text12[1].set_color(GREEN)
        text13 = TextMobject("那么","第二阶段","就可以表示为").to_edge(UP,1.5)
        text13[1].set_color(YELLOW)
        text14 = TexMobject(r"Q_{2}=\frac{x}{2}+\frac{x}{4}").set_color(BLUE_D).next_to(text10,DOWN,0.5)
        text15 = TextMobject("以此类推，我们就可以得到","第$n$阶段","的完成量").to_edge(UP,1.5)
        text15[1].set_color(GREEN)
        text16 = TexMobject(r"\cdots ").next_to(text14,DOWN,0.5)
        text17 = TexMobject(r"Q_{n}=\sum_{i=1}^{n}\frac{x}{2^{i}}  ").next_to(text16,DOWN,0.3).set_color_by_gradient([YELLOW,BLUE_D,ORANGE])

        self.play(ShowCreation(text1))
        self.wait(1)
        self.play(Uncreate(text1))
        self.wait(1)
        self.play(Write(text2))
        self.wait(0.3)
        self.play(Write(text3))
        self.wait(0.3)
        self.play(Write(text4))
        self.wait(2)
        self.play(ReplacementTransform(text_a,text5))
        self.wait(0.1)
        self.play(Write(text6))
        self.wait(2)
        self.play(Write(text8))
        self.wait(2)
        self.play(ReplacementTransform(text8,text9))
        self.play(Write(text10))
        self.wait(2)
        self.play(ReplacementTransform(text9,text11))
        self.wait(2)
        self.play(ReplacementTransform(text11,text12))
        self.wait(2)
        self.play(ReplacementTransform(text12,text13))
        self.play(Write(text14))
        self.wait(2)
        self.play(ReplacementTransform(text13,text15))
        self.play(Write(text16))
        self.wait(1)
        self.play(Write(text17))
        self.wait(3)

class second(Scene):
    def construct(self):
        text1=TextMobject("对于这个式子，运用我们","小学一年级","就会的","等比数列的求和公式").to_edge(UP).scale(0.8)
        text1[1].set_color(YELLOW)
        text1[3].set_color(RED_B)
        text2 = TexMobject(r"Q_{n}=\sum_{i=1}^{n}\frac{x}{2^{i}}  ").set_color_by_gradient([YELLOW,BLUE_D,ORANGE])
        texta = TextMobject("我们不难得到：").to_edge(UP)
        text3= TexMobject(r"Q_{n}=\sum_{i=1}^{n}\frac{x}{2^{i}}=(1-\frac{1}{2^{n}})x").set_color_by_gradient([YELLOW,BLUE_D,ORANGE])
        text4=TextMobject("若要完成作业,就会存在一个第$n$阶段的完成量与总作业量$x$相等").to_edge(UP).scale(0.8)
        text5 = TexMobject(r"\therefore (1-\frac{1}{2^{n}})x = x").set_color(BLUE).to_edge(UP,2.5)
        text6 = TexMobject(r"\because x \neq 0").next_to(text5,DOWN,aligned_edge=LEFT).set_color(RED)
        text7 = TexMobject(r"\therefore",r"1-\frac{1}{2^{n}}=1").next_to(text6,DOWN,aligned_edge=LEFT).set_color(YELLOW)
        text8 = TextMobject("对于上式的成立，必须分两种情况讨论").next_to(text4,DOWN)
        text9 = TextMobject("情况一：").to_edge(LEFT+UP*3.9).set_color(GREEN)
        text10 = TextMobject("当$n$为一个","确切的数","时，发现不存在$n$","使得原式成立").next_to(text8,DOWN,1)
        text10[1].set_color(RED)
        text10[3].set_color(GREEN)
        text11 = TextMobject(r"$\therefore$得到","结论","：","寒假作业是不可能写不完的").next_to(text10,DOWN,1)
        text11[1].set_color(BLUE)
        text11[3].set_color(YELLOW)
        img1 = ImageMobject("doge.png").next_to(text11,RIGHT).scale(0.4)
        text12 = TextMobject("情况二：").to_edge(LEFT+UP*3.9).set_color(GREEN)
        text13 = TextMobject("当","$n\\to +\\infty $","时","原式确实成立").next_to(text8,DOWN,1)
        text13[1].set_color(GREEN)
        text13[3].set_color(YELLOW)
        text14 = TextMobject("但这意味着","，完成作业需要","无穷多个阶段","，","那你还写的完?").next_to(text10,DOWN,1).scale(0.8)
        text14[0].set_color(RED)
        text14[2].set_color(BLUE)
        text14[4].set_color(YELLOW)
        img2 = ImageMobject("doge.png").next_to(text14,RIGHT,-0.5).scale(0.4)
        text15 = TextMobject(r"$\therefore$得到","结论","：","寒假作业是不可能写不完的").next_to(text14,DOWN,1)
        text15[1].set_color(BLUE)
        text15[3].set_color(YELLOW)
        text16 = TextMobject("综上,","寒假作业","是","永远","写不完","的").scale(1.5)
        text16[1].set_color(BLUE_D)
        text16[3].set_color(YELLOW)
        text16[4].set_color(GREEN)
        img3 = ImageMobject("doge.png").next_to(text16,RIGHT,-0.5).scale(0.4)
        text17 = TextMobject("各位学废了吗？").next_to(text16,DOWN,1).scale(0.8).set_color(YELLOW)
        text18 = TextMobject("学废的给个~~~","三连","~~~再走呗,","嘤嘤嘤").next_to(text16,DOWN,1).scale(0.8)
        text18[1].set_color_by_gradient([YELLOW,BLUE_D,GREEN,RED]).scale(2)
        svg1 = SVGMobject("coin.svg", color=BLUE,
                          stoke_width=0.00).next_to(text16, UP, 0.7)
        svg2 = SVGMobject("favo.svg", color=BLUE,
                          stoke_width=0.00).next_to(svg1, RIGHT, 1)
        svg3 = SVGMobject("good.svg", color=BLUE,
                          stoke_width=0.00).next_to(svg1, LEFT, 1)

        self.play(Write(text1),Write(text2))
        self.wait(2)
        self.play(ReplacementTransform(text1,texta))
        self.play(ReplacementTransform(text2,text3))
        self.wait(2)
        self.play(ReplacementTransform(texta,text4))
        self.play(ReplacementTransform(text3,text5))
        self.wait(1)
        self.play(Write(text6))
        self.wait(1)
        self.play(Write(text7))
        self.wait(1)
        self.play(Uncreate(text4),Uncreate(text5),Uncreate(text6),Uncreate(text7[0]))
        self.play(ApplyMethod(text7.shift,4.5*UP))
        self.wait(1)
        self.play(Write(text8))
        self.play(Write(text9))
        self.wait(1)
        self.play(Write(text10))
        self.wait(1)
        self.play(Write(text11),FadeIn(img1))
        self.wait(3)
        self.remove(text10,text11,img1)
        self.play(ReplacementTransform(text9,text12))
        self.wait(1)
        self.play(Write(text13))
        self.wait(1)
        self.play(Write(text14),FadeIn(img2))
        self.wait(1)
        self.play(Write(text15))
        self.wait(3)
        self.play(Uncreate(text8),Uncreate(text12),Uncreate(text13),Uncreate(text14),Uncreate(text15),FadeOut(img2),Uncreate(text7))
        self.wait(1)
        self.play(Write(text16),FadeIn(img3))
        self.wait(1)
        self.play(Write(text17))
        self.wait(1)
        self.play(ReplacementTransform(text17,text18))
        self.play(Write(svg1),Write(svg2),Write(svg3))
        self.wait(4)