from manimlib.imports import *

class zheshetu(Scene):
    def construct(self):
        line_1 = Line(np.array([-4,0,0]),np.array([4,0,0])).set_color(BLACK)
        line_2 = Line(np.array([3,3**0.5,0]),np.array([0,0,0]))
        line_3 = Line(np.array([0,0,0]),np.array([-2,-2.341699132,0]))
        line_4 = DashedLine(np.array([0,3,0]),np.array([0,-3,0])).set_color(BLUE_E)
        vec_1=Arrow(np.array([3,3**0.5,0]),np.array([1.5,(3**0.5)/2,0]),stroke_width = 0)
        vec_2=Arrow(np.array([0,0,0]),np.array([-1,-2.341699132/2,0]),stroke_width = 0)
        VG1 =VGroup(line_2,vec_1).set_color(GREEN_SCREEN)
        VG2 =VGroup(line_3,vec_2).set_color(GREEN_SCREEN)
        arc1=Arc(arc_center=0*LEFT,radius=0.3,stroke_width=4.0,start_angle= 30*DEGREES,angle= 60*DEGREES,color=BLACK) 
        arc2=Arc(arc_center=0*LEFT,radius=0.3,stroke_width=4.0,start_angle= 229*DEGREES,angle= 41*DEGREES,color=BLACK) 
        text1 = TexMobject(r"\theta_{1}").set_color(BLACK).next_to(arc1,0.5*UP+0.01*RIGHT).scale(0.6)
        text2 = TexMobject(r"\theta_{2}").set_color(BLACK).to_edge(6*DOWN+13.3*LEFT).scale(0.6)
        
        self.play(Write(line_1))
        self.wait(0.5)
        self.play(Write(line_4))
        self.wait(0.5)
        self.play(Write(VG1))
        self.play(Write(VG2))
        self.wait(0.5)
        self.play(Write(arc1),Write(text1))
        self.play(Write(arc2),Write(text2))
        self.wait(2)

class fanshetu(Scene):
    def construct(self):
        line_1 = Line(np.array([-4,-1,0]),np.array([4,-1,0])).set_color(BLACK)
        line_2 = Line(np.array([-3,2,0]),np.array([0,-1,0]))
        line_3 = Line(np.array([0,-1,0]),np.array([3,2,0]))
        line_4 = DashedLine(np.array([0,3,0]),np.array([0,-1,0])).set_color(BLUE_E)
        vec_1=Arrow(np.array([-4,3,0]),np.array([-1.3,0.3,0]),stroke_width = 0)
        vec_2=Arrow(np.array([0,-1,0]),np.array([2,1,0]),stroke_width = 0)
        VG1 =VGroup(line_2,vec_1).set_color(GREEN_SCREEN)
        VG2 =VGroup(line_3,vec_2).set_color(GREEN_SCREEN)
        arc1=Arc(arc_center=1*DOWN,radius=0.3,stroke_width=4.0,start_angle= 45*DEGREES,angle= 45*DEGREES,color=BLACK) 
        arc2=Arc(arc_center=1*DOWN,radius=0.3,stroke_width=4.0,start_angle= 90*DEGREES,angle= 45*DEGREES,color=BLACK)
        text1 = TexMobject(r"\theta_{1}").set_color(BLACK).next_to(arc1,UP+0.4*LEFT).scale(0.6)
        text2 = TexMobject(r"\theta_{2}").set_color(BLACK).next_to(arc2,UP+0.4*RIGHT).scale(0.6)

        self.play(Write(line_1))
        self.play(Write(line_4),run_time =0.5)
        self.wait(0.5)
        self.play(Write(VG1))
        self.play(Write(VG2))
        self.play(Write(arc2),Write(text1))
        self.play(Write(arc1),Write(text2))
        self.wait(2)

class frist(Scene):
    def construct(self):
        text1 = TextMobject("相信大家在","学前班","就了解了光的折射这一神奇的现象").to_edge(5*UP)
        text1[1].set_color(GREEN_SCREEN)
        img1 = ImageMobject("zs.jpg",height =4.5,invert = False).next_to(text1,DOWN)
        text2 = TextMobject("到了","小学一年级","我们进一步了解了折射角和入射角之间的数学关系").to_edge(5*UP).scale(0.8)
        text2[1].set_color(RED_E)
        text3 = TexMobject(r"\frac{\sin \theta_{1}}{\sin \theta_{2}}=\frac{v_{1}}{v_{2}}").set_color_by_gradient([YELLOW,GREEN]).next_to(text2,DOWN,2).scale(2)
        text4 = TextMobject("现在，让我们使用小学二年级的知识来证明它吧！").to_edge(5*UP)
        rectangle1 = SurroundingRectangle(text3,fill_opacity = 0).set_color(GREEN)

        
        self.play(Write(text1))
        self.play(FadeIn(img1),run_time = 0.5)
        self.wait(3)
        self.remove(img1)
        self.play(ReplacementTransform(text1,text2))
        self.play(Write(text3))
        self.wait(2)
        self.play(ReplacementTransform(text2,text4))
        self.play(Write(rectangle1))
        self.wait(2)

class second(Scene):
    def construct(self):
        text1 = TextMobject("首先我们要先了解一下著名的","费马原理").to_edge(UP)
        text1[1].set_color(GREEN_SCREEN)
        img1 = ImageMobject("feima.jpg",height =3,invert = False).to_edge(RIGHT*3+UP*4)
        text2 = TextMobject("光沿着所需时间为平稳的路径传播。").next_to(img1,LEFT,1)
        text3 = TextMobject("所谓的平稳是数学上的微分概念，可以理解为一阶导数为零。").to_edge(DOWN*3).scale(0.8).set_color(BLUE_D)
        text4 = TextMobject("它可以是极大值、极小值甚至是拐点。").next_to(text3,DOWN).scale(0.8).set_color(YELLOW)
        text5 = TextMobject("换成数学语言来说，就是").to_edge(UP)
        texta = VGroup(text3,text4)
        text6 = TexMobject(r"\frac{d T}{d x}(x)=0").scale(4).set_color(GOLD)
        
        self.play(Write(text1))
        self.wait(1)
        self.play(Write(text2),FadeIn(img1))
        self.wait(1)
        self.play(Write(text3))
        self.play(Write(text4))
        self.wait(2.5)
        self.play(ReplacementTransform(text1,text5))
        self.remove(text2,img1)
        self.play(ReplacementTransform(texta,text6))
        self.wait(3)

class zst(Scene):
    def construct(self):
        line_1 = Line(np.array([-4,2,0]),np.array([4,2,0]))
        line_2 = Line(np.array([3,(3**0.5)+2,0]),np.array([0,2,0]))
        line_3 = Line(np.array([0,2,0]),np.array([-2,-2.341699132+2,0]))
        line_4 = DashedLine(np.array([0,4-0.5,0]),np.array([0,0.5,0])).set_color(BLUE_E)
        vec_1=Arrow(np.array([3,3**0.5+2,0]),np.array([1.5,((3**0.5)/2)+2,0]),stroke_width = 0)
        vec_2=Arrow(np.array([0,2,0]),np.array([-1,(-2.341699132/2)+2,0]),stroke_width = 0)
        VG1 =VGroup(line_2,vec_1).set_color(GREEN_SCREEN)
        VG2 =VGroup(line_3,vec_2).set_color(GREEN_SCREEN)
        arc1=Arc(arc_center=2*UP,radius=0.3,stroke_width=4.0,start_angle= 30*DEGREES,angle= 60*DEGREES,color=WHITE) 
        arc2=Arc(arc_center=2*UP,radius=0.3,stroke_width=4.0,start_angle= 229*DEGREES,angle= 41*DEGREES,color=WHITE) 
        text1 = TexMobject(r"\theta_{1}").next_to(arc1,0.5*UP+0.01*RIGHT).scale(0.6)
        text2 = TexMobject(r"\theta_{2}").to_edge(10*DOWN+13.3*LEFT).scale(0.6)
        dot1 = Dot(np.array([-4,2,0]))
        dot2 = Dot(np.array([4,2,0]),)
        text3 = TextMobject("A").next_to(dot1,DOWN).scale(0.8)
        text4 = TextMobject("B").next_to(dot2,DOWN).scale(0.8)
        line_5 = DashedLine(np.array([-2,-2.341699132+2,0]),np.array([-2,2,0])).set_color(RED_D)
        text5 = TextMobject("C").next_to(line_5,UP).scale(0.8)
        line_6 = DashedLine(np.array([3,(3**0.5)+2,0]),np.array([3,2,0])).set_color(RED_D)
        text6 = TextMobject("D").next_to(line_6,DOWN).scale(0.8)
        dot3 = Dot(np.array([0,2,0]))
        text7 = TextMobject("O").next_to(dot3,DOWN+RIGHT).scale(0.8)
        dot4 = Dot(np.array([-2,-2.341699132+2,0]))
        text8 = TextMobject("P").next_to(dot4,LEFT).scale(0.8)
        dot5 = Dot(np.array([3,(3**0.5)+2,0]))
        text9 = TextMobject("Q").next_to(dot5,RIGHT).scale(0.8)
        text10 = TexMobject(r"\text{设} C O=x, Q D=b , C D=l").to_edge(DOWN*3)
        text11 = TexMobject(r"x").next_to(dot3,3*LEFT+UP).set_color(GOLD)
        text12 = TexMobject(r"b").next_to(line_6,RIGHT).set_color(GOLD)
        text13 = TexMobject(r"l-x").next_to(dot3,4.5*RIGHT+DOWN).set_color(GOLD)
        text14 = TexMobject(r"\text{不难得到:} Q O=\sqrt{b^{2}+(l-x)^{2}}, P O=\sqrt{a^{2}+x^{2}}").next_to(text10,DOWN).set_color(BLUE_D)
        texta = VGroup(text10,text14)
        text15 = TexMobject(r"\text{现在假设光线在}\uppercase\expandafter{\romannumeral1} \text{、} \uppercase\expandafter{\romannumeral2}\text{中的传播速度分别为} v_{1} \text{、} v_{2}").to_edge(DOWN*3)
        text16 = TexMobject(r"\uppercase\expandafter{\romannumeral1} ").next_to(dot1,2*UP+RIGHT).set_color(YELLOW)
        text17 = TexMobject(r"\uppercase\expandafter{\romannumeral2} ").next_to(dot1,2*DOWN+RIGHT).set_color(YELLOW)
        text18 = TexMobject(r"\text{那么光线从} P \text{到} Q \text{所需时间为:}").to_edge(DOWN*3.5)
        text19 = TexMobject(r"T=\frac{\sqrt{a^{2}+x^{2}}}{v_{1}}+\frac{\sqrt{b^{2}+(l-x)^{2}}}{v_{2}}").next_to(text18,DOWN).set_color(GOLD)
        textb = VGroup(text18,text19)
        text20 = TexMobject(r"\text{于是}\frac{d T}{d x}=\frac{x}{v_{1} \sqrt{a^{2}+x^{2}}}-\frac{l-x}{v_{2} \sqrt{b^{2}+(l-x)^{2}}}").to_edge(DOWN*3).set_color(GOLD)
        text21 = TexMobject(r"\text{利用费马原理，令} \frac{d T}{d x}=0").next_to(text20,DOWN)
        textc = VGroup(text20,text21)
        text22 = TexMobject(r"\text{则} \frac{x}{v_{1} \sqrt{a^{2}+x^{2}}}=\frac{l-x}{v_{2} \sqrt{b_{2}+(l-x)^{2}}}").to_edge(DOWN*3).set_color(GOLD)
        text23 = TexMobject(r"\text{记光线的折射角为} \theta_{1} \text{,入射角为} \theta_{2} \text{,则}").to_edge(DOWN*3.5)
        text24 = TexMobject(r"\sin \theta_{1}=\frac{x}{\sqrt{a^{2}+x^{2}}}, \sin \theta_{2}=\frac{l-x}{\sqrt{b_{2}+(l-x)^{2}}}").next_to(text23,DOWN).set_color(YELLOW)
        text25 = TextMobject("将这个代入上一式中，即得").to_edge(DOWN*3.5)
        text26 = TexMobject(r"\frac{\sin \theta_{1}}{\sin \theta_{2}}=\frac{v_{1}}{v_{2}}").next_to(text23,DOWN).set_color(YELLOW)
        text27 = TextMobject("就这样，我们顺利地得到了我们想要的结果").to_edge(DOWN*3.5).set_color(RED_B)
        rectangle1 = SurroundingRectangle(text26,fill_opacity = .4).set_color(WHITE)

        self.play(Write(line_1))
        self.play(Write(line_4),run_time = 0.5)
        self.play(Write(VG1))
        self.play(Write(VG2))
        self.play(Write(arc1),Write(text1))
        self.play(Write(arc2),Write(text2))
        self.play(Write(dot1),Write(dot2))
        self.play(Write(text3),Write(text4))
        self.wait(1)
        self.play(Write(line_5),Write(text5),Write(line_6),Write(text6),Write(dot3),Write(text7),Write(dot4),Write(text8),Write(dot5),Write(text9))
        self.wait(1)
        self.play(Write(text10))
        self.play(Write(text11))
        self.play(Write(text12))
        self.play(Write(text13))
        self.wait(1)
        self.play(Write(text14))
        self.wait(2)
        self.play(Write(text16),Write(text17))
        self.play(ReplacementTransform(texta,text15))
        self.wait(2)
        self.play(ReplacementTransform(text15,text18))
        self.play(Write(text19))
        self.wait(2)
        self.play(ReplacementTransform(textb,text20))
        self.wait(2)
        self.play(Write(text21))
        self.wait(1)
        self.play(ReplacementTransform(textc,text22))
        self.wait(2)
        self.play(ReplacementTransform(text22,text23))
        self.play(Write(text24))
        self.wait(2)
        self.play(ReplacementTransform(text23,text25))
        self.wait(1)
        self.play(ReplacementTransform(text24,text26))
        self.wait(2)
        self.play(ReplacementTransform(text25,text27))
        self.play(Write(rectangle1))
        self.wait(2)

class HJZY(Scene):
    def construct(self):
        text2 = TextMobject("用同样的方法证明光的反射定律").set_color(YELLOW).to_edge(3*UP).scale(0.8)
        text1 = TextMobject("最后，给大家留一道回家作业").next_to(text2,UP).scale(0.8)
        line_1 = Line(np.array([-4,-3,0]),np.array([4,-3,0]))
        line_2 = Line(np.array([-3,0,0]),np.array([0,-3,0]))
        line_3 = Line(np.array([0,-3,0]),np.array([3,0,0]))
        line_4 = DashedLine(np.array([0,1,0]),np.array([0,-3,0])).set_color(BLUE_E)
        vec_1=Arrow(np.array([-4,1,0]),np.array([-1.3,0.3-2,0]),stroke_width = 0)
        vec_2=Arrow(np.array([0,-3,0]),np.array([2,-1,0]),stroke_width = 0)
        VG1 =VGroup(line_2,vec_1).set_color(GREEN_SCREEN)
        VG2 =VGroup(line_3,vec_2).set_color(GREEN_SCREEN)
        arc1=Arc(arc_center=3*DOWN,radius=0.3,stroke_width=4.0,start_angle= 45*DEGREES,angle= 45*DEGREES,color=WHITE) 
        arc2=Arc(arc_center=3*DOWN,radius=0.3,stroke_width=4.0,start_angle= 90*DEGREES,angle= 45*DEGREES,color=WHITE)
        text3 = TexMobject(r"\theta_{1}").next_to(arc1,1.5*UP+0.4*LEFT).scale(0.8)
        text4 = TexMobject(r"\theta_{2}").next_to(arc2,1.5*UP+0.4*RIGHT).scale(0.8)

        self.play(Write(text1))
        self.play(Write(text2))
        self.wait(0.5)
        self.play(Write(line_1),run_time =0.5)
        self.play(Write(line_4),run_time =0.5)
        self.wait(0.5)
        self.play(Write(VG1),run_time =0.5)
        self.play(Write(VG2),run_time =0.5)
        self.play(Write(arc2),Write(text3),run_time =0.5)
        self.play(Write(arc1),Write(text4),run_time =0.5)
        self.wait(2)

class js(Scene):
    def construct(self):
        text1 = TextMobject("感谢观看").set_color(YELLOW).to_edge(4*UP)
        svg1 = SVGMobject("coin.svg",color=BLUE,stoke_width = 0.00).next_to(text1,DOWN,0.7)
        svg2 = SVGMobject("favo.svg",color=BLUE,stoke_width = 0.00).next_to(svg1,RIGHT,1)
        svg3 = SVGMobject("good.svg",color=BLUE,stoke_width = 0.00).next_to(svg1,LEFT,1)
        text3 = TexMobject(r"\uparrow").set_color(RED).next_to(svg1,DOWN*2).scale(0.6)
        text2 = TextMobject("(疯狂暗示)").set_color(RED).next_to(text3,DOWN).scale(0.6)

        self.play(Write(text1))
        self.wait(1)
        self.play(ShowCreation(svg1),ShowCreation(svg2),ShowCreation(svg3))
        self.play(Write(text3),Write(text2))
        self.wait(4)