from operator import ne
from tkinter import W
from weakref import WeakKeyDictionary
from manimlib.imports import *
from manim_sandbox.utils.imports import *
from math import *
from NumberCreature.NumberCreature import *


class yinru(Scene):
    def construct(self):
        text1 = TextMobject(r"~~~~~~~~~如果求知欲、职业自尊心和雄心是从事研究的主要动机，\\那么毫无疑问，数学家是最有机会具备这些动机的人群了。").scale(0.8)
        text2 = TextMobject("——戈弗雷·哈代").shift(4*RIGHT+DOWN).scale(0.8)
        textA = VGroup(text1,text2)

        self.play(FadeIn(text1),run_time=2)
        self.play(FadeIn(text2),run_time=1)
        self.wait(4)
        self.play(FadeOut(textA),run_time=2)


class frist(Scene):
    def construct(self):
        text1 =TextMobject("化学方程式","作为化学家们","通用的语言","，是","化学计算","的","重要基础").to_edge(DOWN).scale(0.8)
        text1[0].set_color(GOLD_B)
        text1[2].set_color(GREEN)
        text1[4].set_color(BLUE)
        text1[6].set_color(RED)
        tex1 = TexMobject(r"As_{4}+H_{2}O\triangleq As_{2}O_{3}+H_{2}\uparrow").shift(UP)
        text2 = TextMobject("但在运用它计算前，我们必须将其","配平").to_edge(DOWN)
        text2[1].set_color(RED)
        tex3 = TexMobject(r"\Downarrow").next_to(tex1,DOWN)
        tex2 = TexMobject(r"1As_{4}+6H_{2}O\triangleq 2As_{2}O_{3}+6H_{2}\uparrow").next_to(tex3,DOWN)
        tex2[0][0].set_color(GREEN_D)
        tex2[0][5].set_color(GREEN_D)
        tex2[0][10].set_color(GREEN_D)
        tex2[0][17].set_color(GREEN_D)
        text3 = TextMobject("对于简单方程式，可以使用较为灵活的方法配平").to_edge(DOWN)
        texA = VGroup(tex1,tex2,tex3,text2)
        tex4 = TexMobject(r"H_{2}+O_{2}=H_{2}O").scale(0.9).shift(LEFT*4)
        tex5 = TexMobject(r"2H_{2}+O_{2}=2H_{2}O").scale(0.9).shift(RIGHT*4)
        vec1 = Arrow(np.array([-2,0,0]),np.array([2,0,0]))
        text4 = TextMobject("观察法 ").next_to(vec1,UP,-0.1).scale(0.6).set_color(YELLOW)
        text5 = TextMobject("奇偶法 ").next_to(text4,UP).scale(0.6).set_color(PURPLE)
        text6 = TextMobject("最小公倍数法").next_to(vec1,DOWN,-0.1).scale(0.6).set_color(GREEN)
        text7 = TextMobject("氧化还原法").next_to(text6,DOWN).scale(0.6).set_color(ORANGE)
        textA = VGroup(text4,text5,text6,text7)
        text8 = TextMobject("但对于复杂且没有特征的方程式，这些方法就不太行").to_edge(DOWN)
        cro = Cross(textA,stroke_color=RED,stroke_width =3)
        text9 = TextMobject("复杂的方程式（大雾）").next_to(vec1,LEFT).set_color(YELLOW)
        text10 = TextMobject("?").scale(3).next_to(vec1,RIGHT,1.5).set_color(RED)
        text11 =TextMobject("遇到这种情况不要紧张，答案可能是","钝角","(bushi").to_edge(DOWN)
        text11[1].set_color(YELLOW)
        text11[2].set_color(BLUE)
        text12 =TextMobject("这种情况下，我们可以借助矩阵的相关知识进行求解").to_edge(DOWN)
        text13 =TextMobject("复杂的方程式").shift(LEFT*2.5).set_color(YELLOW)
        tex6 = TexMobject(r"\begin{bmatrix}a&b&c\\d&e&f\\g&h&i\end{bmatrix}").shift(RIGHT*2.5)
        arc1 = Arc(start_angle=5*pi/6, angle=-2*pi/3).add_tip(tip_length=None, at_start=0)

        self.play(Write(text1))
        self.play(Write(tex1))
        self.wait(2)
        self.play(ReplacementTransform(text1,text2))
        self.wait(0.5)
        self.play(Write(tex3))
        self.play(Write(tex2))
        self.wait(2)
        self.play(Uncreate(texA))
        self.play(Write(tex4))
        self.play(Write(text3))
        self.wait(0.5)
        self.play(Write(vec1))
        self.play(FadeIn(textA))
        self.play(Write(tex5))
        self.wait(1)
        self.play(ReplacementTransform(text3,text8))
        self.wait(0.5)
        self.play(ReplacementTransform(tex4,text9))
        self.wait(0.5)
        self.play(ReplacementTransform(tex5,text10))
        self.wait(0.5)
        self.play(Write(cro))
        self.wait(1)
        self.play(ReplacementTransform(text8,text11))
        self.wait(1)
        self.remove(text9,cro,textA,vec1,text10,text11)
        self.wait(2)
        self.play(Write(text13))
        self.wait(2)
        self.play(Write(text12))
        self.wait(1)
        self.play(Write(tex6))
        self.play(Write(arc1),ApplyWave(tex6))
        self.wait(2)


class yuanliyuyuanze(Scene):
    def construct(self):
        text1 = TextMobject("$\mathfrak{A}$.","原理","或","原则").scale(2).set_color_by_gradient([GOLD,GREEN,WHITE])
        text2 = TextMobject("我们知道任何化学反应满足质量守恒定律").to_edge(DOWN)
        text3 = TextMobject("质量守恒定律").shift(LEFT*5).scale(0.8)
        text4 = TextMobject("其中比较重要的两点如上所示").to_edge(DOWN)
        tex1 = TexMobject(r"\begin{cases}\text{反应前后，原子的种类不变}\\\text{反应前后，原子的数目不变}\end{cases}").shift(LEFT).scale(0.8)
        tex1[0][1:13].set_color(RED)
        tex1[0][13:25].set_color(GREEN)
        text5 = TextMobject("其中第二点准确的描述了元素的数量关系").to_edge(DOWN)
        re1 = SurroundingRectangle(tex1[0][13:25],fill_opacity = 0.3).set_color(YELLOW)
        vec1 = Arrow(np.array([1.65,-0.25,0]),np.array([3.65,-0.25,0]))
        text6 = TextMobject("数量关系").next_to(vec1,RIGHT).set_color(BLUE_A)
        text7 = TextMobject("依此可将任何一条方程式的数量关系写出来").to_edge(DOWN)
        tex2  = TexMobject(r"x_{1}NCl_{3}+x_{2}H_{2}O \rightleftharpoons x_{3}HClO + x_{4}NH_{4}").shift(UP*2)
        tex2[0][0:2].set_color(GREEN)
        tex2[0][7:9].set_color(YELLOW)
        tex2[0][13:15].set_color(BLUE)
        tex2[0][20:22].set_color(RED)
        text8 = TextMobject("设一未配平的方程式个物质前系数为","$x_{n}$","，并列出方程组").to_edge(DOWN)
        text8[1].set_color(YELLOW)
        tex3 = TexMobject(r"\begin{cases}1·x_{1}+0·x_{2}=0·x_{3}+1·x_{4}\\3·x_{1}+0·x_{2}=1·x_{3}+0·x_{4}\\0·x_{1}+2·x_{2}=1·x_{3}+3·x_{4}\\0·x_{1}+1·x_{2}=1·x_{3}+0·x_{4}\end{cases}").scale(0.7).to_edge(LEFT*2)
        tex3[0][11:13].set_color(GREEN)
        tex3[0][30:32].set_color(GREEN)
        tex3[0][49:51].set_color(GREEN)
        tex3[0][68:70].set_color(GREEN)
        tex3[0][16:18].set_color(YELLOW)
        tex3[0][35:37].set_color(YELLOW)
        tex3[0][54:56].set_color(YELLOW)
        tex3[0][73:75].set_color(YELLOW)
        tex3[0][21:23].set_color(BLUE)
        tex3[0][40:42].set_color(BLUE)
        tex3[0][59:61].set_color(BLUE)
        tex3[0][78:80].set_color(BLUE)
        tex3[0][26:28].set_color(RED)
        tex3[0][45:47].set_color(RED)
        tex3[0][64:66].set_color(RED)
        tex3[0][83:85].set_color(RED)
        tex4 = TexMobject(r"\begin{cases}1·x_{1}+0·x_{2}-0·x_{3}-1·x_{4}=0\\3·x_{1}+0·x_{2}-1·x_{3}-0·x_{4}=0\\0·x_{1}+2·x_{2}-1·x_{3}-3·x_{4}=0\\0·x_{1}+1·x_{2}-1·x_{3}-0·x_{4}=0\end{cases}").scale(0.7).to_edge(RIGHT*2)
        tex4[0][11:13].set_color(GREEN)
        tex4[0][32:34].set_color(GREEN)
        tex4[0][53:55].set_color(GREEN)
        tex4[0][74:76].set_color(GREEN)
        tex4[0][16:18].set_color(YELLOW)
        tex4[0][37:39].set_color(YELLOW)
        tex4[0][58:60].set_color(YELLOW)
        tex4[0][79:81].set_color(YELLOW)
        tex4[0][21:23].set_color(BLUE)
        tex4[0][42:44].set_color(BLUE)
        tex4[0][63:65].set_color(BLUE)
        tex4[0][84:86].set_color(BLUE)
        tex4[0][26:28].set_color(RED)
        tex4[0][47:49].set_color(RED)
        tex4[0][68:70].set_color(RED)
        tex4[0][89:91].set_color(RED)
        text9 = TextMobject("稍作整理可得一个齐次线性方程组").to_edge(DOWN)
        text10 = TextMobject("写出与其对应的系数矩阵").to_edge(DOWN)
        tex5 = TexMobject(r"\Longrightarrow").shift(0.25*RIGHT)
        tex6 = TexMobject(r"\begin{bmatrix}1&0&0&-1\\3&0&-1&0\\0&2&-1&-3\\0&1&-1&0\end{bmatrix}").next_to(tex5,RIGHT)
        tex7 = TexMobject(r"\begin{bmatrix}1&0&0&-1\\3&0&-1&0\\0&2&-1&-3\\0&1&-1&0\end{bmatrix}").next_to(tex2,DOWN,1)
        textA = VGroup(tex7[0][4],tex7[0][9],tex7[0][14],tex7[0][20])
        textB = VGroup(tex7[0][5],tex7[0][10],tex7[0][15],tex7[0][21])
        textC = VGroup(tex7[0][6],tex7[0][11:13],tex7[0][16:18],tex7[0][22:24])
        textD = VGroup(tex7[0][7:9],tex7[0][13],tex7[0][18:20],tex7[0][24])
        textE = VGroup(tex7[0][4:9])
        textF = VGroup(tex7[0][9:14])
        textG = VGroup(tex7[0][14:20])
        textH = VGroup(tex7[0][20:25])
        re2 = SurroundingRectangle(textE,fill_opacity = 0.3).set_color(YELLOW)
        re3 = SurroundingRectangle(textF,fill_opacity = 0.3).set_color(GREEN)
        re4 = SurroundingRectangle(textG,fill_opacity = 0.3).set_color(RED)
        re5 = SurroundingRectangle(textH,fill_opacity = 0.3).set_color(PURPLE)
        text11 = TextMobject("可以发现矩阵的每一行分别对应反应中的一种元素").to_edge(DOWN)
        text12 = TextMobject("N").next_to(textE,LEFT).set_color(YELLOW)
        text13 = TextMobject("Cl").next_to(textF,LEFT).set_color(GREEN)
        text14 = TextMobject("H").next_to(textG,LEFT).set_color(RED)
        text15 = TextMobject("O").next_to(textH,LEFT).set_color(PURPLE)
        textK = VGroup(text12,text13,text14,text15)
        text16 = TextMobject("而每一列表示对应元素在对应物质中的数量").to_edge(DOWN)
        re6 = SurroundingRectangle(textA,fill_opacity = 0.3).set_color(GREEN)
        re7 = SurroundingRectangle(textB,fill_opacity = 0.3).set_color(YELLOW)
        re8 = SurroundingRectangle(textC,fill_opacity = 0.3).set_color(BLUE)
        re9 = SurroundingRectangle(textD,fill_opacity = 0.3).set_color(RED)
        text17 = TextMobject("$NCl_{3}$").next_to(textA,UP).set_color(GREEN).scale(0.6)
        text18 = TextMobject("$H_{2}O$").next_to(textB,UP).set_color(YELLOW).scale(0.6)
        text19 = TextMobject("HClO").next_to(textC,UP).set_color(BLUE).scale(0.6)
        text20 = TextMobject("$NH_{4}$").next_to(textD,UP).set_color(RED).scale(0.6)
        text21 = TextMobject("根据实际意义，一个矩阵分为反应区和生成区").to_edge(DOWN)
        textL = VGroup(text17,text18,text19,text20)
        textI = VGroup(tex7[0][4],tex7[0][9],tex7[0][14],tex7[0][20],tex7[0][5],tex7[0][10],tex7[0][15],tex7[0][21])
        textJ = VGroup(tex7[0][6],tex7[0][11:13],tex7[0][16:18],tex7[0][22:24],tex7[0][7:9],tex7[0][13],tex7[0][18:20],tex7[0][24])
        re10 = SurroundingRectangle(textI,fill_opacity = 0.3).set_color(WHITE)
        re11 = SurroundingRectangle(textJ,fill_opacity = 0.3).set_color(LIGHT_BROWN)
        text22 = TextMobject("反应区").next_to(re10,DOWN)
        text23 = TextMobject("生成区").next_to(re11,DOWN).set_color(LIGHT_BROWN)
        text24 = TextMobject("(非负数)").shift(DOWN*2.7+LEFT*1.2).scale(0.6).set_color(RED)
        text25 = TextMobject("(非正数)").shift(DOWN*2.7+RIGHT*0.8).scale(0.6).set_color(RED)
        text26 = TextMobject("需要注意，反应区所有数值写为非负数").to_edge(DOWN)
        text27 = TextMobject("生成区所有数量写为非正数").to_edge(DOWN)
        text28 = TextMobject("至此，我们学会了对于一切方程式").to_edge(DOWN)
        text29 = TextMobject("都可以写出它对应的系数矩阵").to_edge(DOWN)
        tex8 = TexMobject(r"NCl_{3}+H_{2}O \rightleftharpoons HClO+NH_{3}").scale(0.9).shift(UP).to_edge(LEFT*2).set_color(GREEN)
        tex9 = TexMobject(r"Ce_{2}O_{3}+O_{2} \triangleq CeO_{2}").scale(0.9).shift(DOWN).to_edge(LEFT*2).set_color(BLUE)
        vec2 = Arrow(np.array([0.35,1.05,0]),np.array([2.35,1.05,0])).set_color(GREEN)
        vec3 = Arrow(np.array([-2,-1,0]),np.array([2.35,-1,0])).set_color(BLUE)
        tex10 = TexMobject(r"\begin{bmatrix}1&0&0&-1\\3&0&-1&0\\0&2&-1&-3\\0&1&-1&0\end{bmatrix}").next_to(vec2,RIGHT).set_color(GREEN)
        tex11 = TexMobject(r"\begin{bmatrix}2&0&-1\\3&2&-2\end{bmatrix}").next_to(vec3,RIGHT).set_color(BLUE)

        self.play(FadeInFrom(text1,DOWN))
        self.wait(1)
        self.play(FadeOut(text1))
        self.wait(1)
        self.play(Write(text2))
        self.play(Write(text3))
        self.wait(1)
        self.play(ReplacementTransform(text2,text4))
        self.play(Write(tex1))
        self.wait(1.5)
        self.play(ReplacementTransform(text4,text5))
        self.play(Write(re1))
        self.play(Write(vec1))
        self.play(Write(text6))
        self.wait(1.5)
        self.play(FadeOutAndShift(text3,DOWN),FadeOutAndShift(tex1[0][0],UP),FadeOutAndShift(tex1[0][1:25],DOWN),FadeOutAndShift(vec1,UP),FadeOutAndShift(text6,DOWN),FadeOutAndShift(re1,UP))
        self.play(ReplacementTransform(text5,text7))
        self.play(Write(tex2))
        self.wait(2)
        self.play(ReplacementTransform(text7,text8))
        self.wait(2)
        self.play(TransformFromCopy(tex2,tex3))
        self.wait(3)
        self.play(ReplacementTransform(text8,text9))
        self.play(TransformFromCopy(tex3,tex4))
        self.wait(3)
        self.play(FadeOut(tex3))
        self.play(tex4.to_edge,LEFT*2)
        self.wait(1)
        self.play(ReplacementTransform(text9,text10))
        self.wait(1)
        self.play(Write(tex5),Write(tex6))
        self.wait(2)
        self.play(FadeOutAndShift(tex4,DOWN),FadeOutAndShift(tex5,UP))
        self.play(tex6.next_to,tex2,DOWN,1)
        self.add(tex7)
        self.remove(tex6)
        self.play(ReplacementTransform(text10,text11))
        self.play(Write(re2),Write(re3),Write(re4),Write(re5))
        self.play(Write(text12),Write(text13),Write(text14),Write(text15))
        self.wait(2)
        self.play(FadeOut(re2),FadeOut(re3),FadeOut(re4),FadeOut(re5))
        self.play(ReplacementTransform(text11,text16))
        self.play(Write(re6),Write(re7),Write(re8),Write(re9))
        self.play(Write(text20),Write(text17),Write(text18),Write(text19))
        self.wait(2)
        self.play(FadeOut(re6),FadeOut(re7),FadeOut(re8),FadeOut(re9))
        self.play(ReplacementTransform(text16,text21))
        self.play(Write(re10),Write(re11))
        self.play(Write(text22),Write(text23))
        self.wait(2)
        self.play(ReplacementTransform(text21,text26))
        self.play(Write(text24))
        self.wait(1)
        self.play(ReplacementTransform(text26,text27))
        self.play(Write(text25))
        self.wait(2)
        self.play(ReplacementTransform(text27,text28))
        self.play(FadeOut(textK),FadeOut(textL),FadeOut(re10),FadeOut(re11),FadeOut(text22),FadeOut(text23),FadeOut(text24),FadeOut(text25),FadeOut(tex2),FadeOut(tex7))
        self.play(Write(tex8),Write(tex9))
        self.play(ReplacementTransform(text28,text29))
        self.play(Write(vec2),Write(vec3))
        self.play(Write(tex10),Write(tex11))
        self.wait(2)



class qiujie(Scene):
    def construct(self):
        text1 = TextMobject("$\mathfrak{B}$.求解方式").scale(2).set_color_by_gradient([RED,GREEN,BLUE])
        text2 = TextMobject("写出对应的系数矩阵后，尝试求出它的基础解系").to_edge(DOWN)
        tex1  = TexMobject(r"x_{1}NCl_{3}+x_{2}H_{2}O \rightleftharpoons x_{3}HClO + x_{4}NH_{4}").shift(UP*2)
        tex1[0][0:2].set_color(GREEN)
        tex1[0][7:9].set_color(YELLOW)
        tex1[0][13:15].set_color(BLUE)
        tex1[0][20:22].set_color(RED)
        tex2 = TexMobject(r"\begin{bmatrix}1&0&0&-1\\3&0&-1&0\\0&2&-1&-3\\0&1&-1&0\end{bmatrix}")
        text3 = TextMobject("求解齐次线性方程组通常选用初等行变换").to_edge(DOWN)
        text4 = TextMobject("将矩阵化为行阶梯形矩阵").to_edge(DOWN)
        tex4 = TexMobject(r"\begin{bmatrix}1&0&0&-1\\3&0&-1&0\\0&2&-1&-3\\0&1&-1&0\end{bmatrix}").to_corner(UL).scale(0.7)
        tex3  = TexMobject(r"\overset{\underset{r}{}}{\sim}").next_to(tex4,RIGHT).shift(UP*0.1)
        tex5 = TexMobject(r"\begin{bmatrix}1&0&0&-1\\0&0&-1&3\\0&2&-1&-3\\0&1&-1&0\end{bmatrix}").next_to(tex4,RIGHT,1).scale(0.7).set_color(GREEN)
        tex6  = TexMobject(r"\overset{\underset{r}{}}{\sim}").next_to(tex5,RIGHT).shift(UP*0.1)
        texA = VGroup(tex4,tex3)
        texB = VGroup(tex5,tex6).shift(LEFT*0.7)
        tex7 = TexMobject(r"\begin{bmatrix}1&0&0&-1\\0&0&-1&3\\0&1&-1&0\\0&0&1&3\end{bmatrix}").next_to(tex5,RIGHT,1).scale(0.7).set_color(RED)
        tex8  = TexMobject(r"\overset{\underset{r}{}}{\sim}").next_to(tex7,RIGHT).shift(UP*0.1)
        texC = VGroup(tex7,tex8).shift(LEFT*0.7)
        tex9 = TexMobject(r"\begin{bmatrix}1&0&0&-1\\0&1&-1&0\\0&0&-1&3\\0&0&0&0\end{bmatrix}").next_to(tex7,RIGHT,1).scale(0.7).shift(LEFT*0.7).set_color(GOLD)
        re1 = SurroundingRectangle(tex9,fill_opacity = 0.5).set_color(GREEN)
        text5 = TextMobject("行阶梯形矩阵").scale(0.7).next_to(re1,DOWN)
        tex10 = TexMobject(r"\begin{bmatrix}1&0&0&-1\\0&1&-1&0\\0&0&-1&3\\0&0&0&0\end{bmatrix}").set_color(GOLD)
        text6 = TextMobject("经观察，$x_{4}$为自由变量").to_edge(DOWN)
        texD = VGroup(tex10[0][7:9],tex10[0][13],tex10[0][18],tex10[0][22])
        re2 = SurroundingRectangle(texD,fill_opacity = 0.5).set_color(RED)
        tex11 = TexMobject(r"x_{4}").next_to(re2,UP).set_color(RED)
        text7 = TextMobject("对$x_{4}$赋值为1，自下向上求解方程").to_edge(DOWN)
        tex12 = TexMobject(r"\text{令}x_{4}=1").shift(DOWN*2+LEFT*2.3).scale(0.8)
        vec1 = Arrow(np.array([2.3,-1.6,0]),np.array([2.3,1.6,0]))
        tex13 = TexMobject(r"\Longrightarrow ").next_to(tex12,RIGHT).scale(0.8)
        tex14 = TexMobject(r"\xi = (1,3,3,1)^{T}").scale(1.3).next_to(tex13,RIGHT).set_color_by_gradient([RED,GREEN,WHITE])
        text8 = TextMobject("解得基础解系只有一个解向量的").to_edge(DOWN)
        re3 = SurroundingRectangle(tex14,fill_opacity = 0.0).set_color(WHITE)
        tex15 = TexMobject(r"\xi = (1,3,3,1)^{T}").scale(1.3).to_edge(UP)
        text9 = TextMobject("对于方程组来说，解可以是该解向量的任意倍").to_edge(DOWN)
        tex16 = TexMobject(r"\forall k \in \mathbb{R}, k \xi=\begin{cases}(1,3,3,1),k=1\\(\frac{1}{2},\frac{3}{2},\frac{3}{2},\frac{1}{2}),k=\frac{1}{2}\\(2,6,6,2),k = 2\\ kkkkkk\vdots kkkkkk \end{cases}")
        tex16[0][68:71].set_color(BLACK)
        tex16[0][80:83].set_color(BLACK)
        tex16[0][71:74].set_color(BLACK)
        tex16[0][77:80].set_color(BLACK)
        text10 = TextMobject("但对于方程式，一般选取整数且互素的解作为配平系数").to_edge(DOWN)
        re4 = SurroundingRectangle(tex16[0][19:32],fill_opacity = 0.5).set_color(GREEN)
        text11 = TexMobject(r"\surd ").next_to(tex16[0][19:32],RIGHT).set_color(GREEN)
        cro1 = Cross(tex16[0][32:55])
        cro2 = Cross(tex16[0][55:68])
        cro3 = Cross(tex16[0][71:80])
        text12 = TextMobject("对于有些方程式，依法求解后可以得到多个线性无关的解向量").to_edge(DOWN)
        tex17 = TexMobject(r"S_{0}=\{\eta_{1},\eta_{2},\eta_{3}\cdots,\eta_{n}\}").to_edge(UP)
        text13 = TextMobject("则解可以是多个线性无关的解向量的任意线性组合").to_edge(DOWN)
        tex18 = TexMobject(r"\forall k_{n} \in \mathbb{R}, \sum_{i = 1}^{n}k_{i}\eta_{i}=\begin{cases}\eta_{1}+\eta_{2}+\eta_{3}+\cdots+\eta_{n}\\3\eta_{1}-\eta_{2}+5\eta_{3}+ \cdots + 3\eta_{n}\\-2\eta_{1}+3\eta_{2}-\frac{1}{2}\eta_{3}+\cdots-6\eta_{n}\\~~~~~~~~~~~~~~~~~~~~\vdots\end{cases}").to_edge(LEFT).shift(UP)
        text14 = TextMobject("在这种情况下，需要相关化学规律来进一步确定").to_edge(DOWN)
        tex19 = TexMobject(r"\Downarrow ").shift(DOWN+LEFT*4)
        text16 = TextMobject("满足相关化学规律").scale(0.7).next_to(tex19,DOWN).set_color(BLUE_B)
        tex21 = TexMobject(r"\Rightarrow").next_to(text16,RIGHT)
        tex20 = TexMobject(r"\xi = (x_{1},x_{2},x_{3} \cdots x_{m)^{T}").scale(1.3).next_to(tex21,RIGHT).set_color(GOLD)
        re5 = SurroundingRectangle(tex20,fill_opacity = 0.5).set_color(GREEN)
        text15 = TextMobject("至此，我们已经学会运用矩阵来求解方程式的配平系数").to_edge(DOWN)
        text17 = TexMobject(r"\surd ").next_to(re5,RIGHT).set_color(GREEN)
        tex22 = TexMobject(r"\begin{bmatrix}1&0&0&-1\\3&0&-1&0\\0&2&-1&-3\\0&1&-1&0\end{bmatrix}").shift(LEFT*3)
        tex23 =TexMobject(r"\xi = \begin{bmatrix}1\\3\\3\\1\end{bmatrix}").shift(RIGHT*2).set_color(GOLD)
        arc1 = Arc(start_angle=5*pi/6, angle=-2*pi/3).add_tip(tip_length=None, at_start=0)

        self.play(FadeInFrom(text1,DOWN))
        self.wait(1)
        self.play(FadeOut(text1))
        self.wait(1)
        self.play(Write(text2))
        self.play(Write(tex1),Write(tex2))
        self.wait(2)
        self.play(FadeOut(tex1))
        self.play(tex2.scale,0.7)
        self.play(tex2.next_to,tex4,0)
        self.wait(1)
        self.play(ReplacementTransform(text2,text3))
        self.wait(1)
        self.play(Write(tex3))
        self.add(tex4)
        self.remove(tex2)
        self.wait(1)
        self.play(ReplacementTransform(text3,text4),TransformFromCopy(texA,texB))
        self.wait(1)
        self.play(TransformFromCopy(texB,texC))
        self.wait(1)
        self.play(TransformFromCopy(texC,tex9))
        self.wait(1)
        self.play(Write(re1),Write(text5))
        self.wait(1.5)
        self.play(FadeOut(texA),FadeOut(texB),FadeOut(texC),FadeOut(re1),FadeOut(text5))
        self.play(tex9.move_to,np.array([0,0,0]))
        self.play(tex9.scale,1/0.7)
        self.add(tex10)
        self.remove(tex9)
        self.wait(1)
        self.play(ReplacementTransform(text4,text6))
        self.play(Write(re2),Write(tex11))
        self.wait(1)
        self.play(ReplacementTransform(text6,text7))
        self.play(Write(tex12))
        self.play(Write(vec1))
        self.wait(1.5)
        self.play(ReplacementTransform(text7,text8))
        self.play(Write(tex13))
        self.play(Write(tex14))
        self.play(Write(re3))
        self.wait(1.5)
        self.play(FadeOut(re3),FadeOut(tex12),FadeOut(tex13),FadeOut(re2),FadeOut(tex11),FadeOut(tex10),FadeOut(vec1))
        self.play(ReplacementTransform(tex14,tex15))
        self.play(ReplacementTransform(text8,text9))
        self.wait(1)
        self.play(Write(tex16))
        self.wait(2)
        self.play(ReplacementTransform(text9,text10))
        self.play(Write(cro1),Write(cro2),Write(cro3))
        self.play(Write(re4),Write(text11))
        self.wait(2)
        self.play(FadeOut(tex15),FadeOut(tex16),FadeOut(re4),FadeOut(text11),FadeOut(cro1),FadeOut(cro2),FadeOut(cro3))
        self.play(ReplacementTransform(text10,text12))
        self.play(Write(tex17))
        self.wait(2)
        self.play(ReplacementTransform(text12,text13))
        self.wait(2)
        self.play(Write(tex18))
        self.play(ReplacementTransform(text13,text14))
        self.play(Write(tex19),Write(text16))
        self.play(Write(tex21))
        self.play(Write(tex20))
        self.play(Write(re5))
        self.play(Write(text17))
        self.wait(2)
        self.play(FadeOutAndShift(tex17,DOWN),FadeOutAndShift(tex18,UP),FadeOutAndShift(text16,DOWN),FadeOutAndShift(tex19,UP),FadeOutAndShift(tex21,DOWN),FadeOutAndShift(re5,UP),FadeOutAndShift(tex20,DOWN),FadeOutAndShift(text17,UP))
        self.play(ReplacementTransform(text14,text15))
        self.play(Write(tex22))
        self.play(Write(arc1))
        self.play(Write(tex23))
        self.wait(2)

class zhiyuwuzhiliang(Scene):
    def construct(self):
        text1 = TextMobject("$\mathfrak{C}$.秩与物质数量的关系").scale(2).set_color_by_gradient([Lime,ORANGE,WHITE])
        text2 = TextMobject("上节中，我们知道方程式对应的线性方程可能存在多个线性无关的解").to_edge(DOWN).scale(0.8)
        text3 = TextMobject("也可能只存在唯一一个解").to_edge(DOWN)
        tex1 = TexMobject(r"S_{0} = \{\eta_{1},\eta_{2},\eta_{3}\ \cdots \eta_{n}\}").shift(UP*0.5).shift(LEFT*4).set_color(GREEN)
        tex2 = TexMobject(r"\text{!}\xi = (1,3,3,1)^{T}").shift(DOWN*0.5).shift(LEFT*4).set_color(BLUE)
        text4  = TextMobject("关于这种现象，必须引入重要的概念——矩阵的秩").to_edge(DOWN)
        tex3 = TexMobject(r"\text{秩}(\mathcal{R} \mathcal{A} \mathcal{N} \mathcal{K}  )").shift(RIGHT*4).set_color_by_gradient([ORANGE,WHITE,BLUE])
        vec1 = Arrow(np.array([-1,0,0]),np.array([2.5,0,0]))
        text5 = TextMobject("根据线性代数理论，矩阵的秩与未知数数量关系可以判断解的数量").to_edge(DOWN).scale(0.8)
        tex4= TexMobject(r"\text{矩阵的秩}r(A)+\text{未知数数量}n\Rightarrow \text{解的情况} ").set_color(YELLOW)
        text6 = TextMobject("在这个问题中，未知数数量$n$即整个反应中涉及的物质数量").scale(0.8).to_edge(DOWN)
        text7 = TextMobject("(涉及物质的数量)").scale(0.7).next_to(tex4[0][9:15],DOWN).set_color(RED)
        tex5 = TexMobject(r"\uppercase\expandafter{\romannumeral1}.r(A)=n-1").to_corner(UL)
        tex5[0][2:6].set_color(RED)
        tex5[0][7:10].set_color(YELLOW)
        line1 = Line(np.array([-10,2.8,0]),np.array([10,2.8,0]))
        text8 = TextMobject("对于大部分反应，矩阵的秩比总物质数量少1").to_edge(DOWN)
        text9 = TextMobject("(大部分反应)").next_to(tex5,RIGHT).set_color(Lime)
        text10 = TextMobject("以三氯化氮与水反应为例，写出方程式和对应矩阵").to_edge(DOWN)
        tex6 = TexMobject(r"NCl_{3}+H_{2}O=HClO+NH_{3}").next_to(line1,DOWN)
        tex7 = TexMobject(r"\begin{bmatrix}1&0&0&-1\\3&0&-1&0\\0&2&-1&-3\\0&1&-1&0\end{bmatrix}")
        tex6_5 =TexMobject(r"A=").next_to(tex7,LEFT)
        text11 = TextMobject("并对其初等行变换，将其化为行阶梯形矩阵").to_edge(DOWN)
        tex8 = TexMobject(r"\begin{bmatrix}1&0&0&-1\\0&1&-1&0\\0&0&-1&3\\0&0&0&0\end{bmatrix}").set_color(GOLD)
        text12 = TextMobject("可以看出，矩阵的秩$r(A)=3$").to_edge(DOWN)
        re1 = SurroundingRectangle(tex8[0][4:18],fill_opacity = 0.5).set_color(RED)
        re2 = SurroundingRectangle(tex8[0][19:23],fill_opacity = 0.5).set_color(Lime)
        tex9 =TexMobject(r"r(A)=3").shift(DOWN*2+LEFT*2)
        tex10 = TexMobject(r"=n-1").next_to(tex9,RIGHT).set_color(RED).shift(UP*0.1)
        text13 = TextMobject("与涉及物质数量少1").to_edge(DOWN)
        tex11 = TexMobject(r"\Rightarrow \text{只有一个解向量}").next_to(tex10,RIGHT)
        text14 = TextMobject("根据线性代数理论，可得方程只有一个解向量").to_edge(DOWN)
        tex12 = TexMobject(r"\uppercase\expandafter{\romannumeral2}.r(A)<n-1").to_corner(UL)
        tex12[0][3:7].set_color(RED)
        tex12[0][8:11].set_color(YELLOW)
        text15 = TextMobject("存在一类方程式，矩阵的秩小于总物质数量少1").to_edge(DOWN)
        text16 = TextMobject("以氯化硒与过氧化钠反应为例，写出方程式和对应矩阵").to_edge(DOWN)
        tex16_5 = TexMobject(r"Se_{2}Cl_{2}+Na_{2}O_{2}=Na_{2}SeO_{3}+Na_{2}SeO_{4}+NaCl+Se").next_to(line1,DOWN)
        tex17 = TexMobject(r"\begin{bmatrix}2&0&-1&-1&0&-1\\2&0&0&0&-1&0\\0&2&-2&-2&-1&0\\0&-2&-3&-4&0&0\end{bmatrix}").scale(0.8)
        tex18 = TexMobject(r"B=").next_to(tex17,LEFT)
        text17 = TextMobject("并对其初等行变换，将其化为行阶梯形矩阵").to_edge(DOWN)
        tex19 = TexMobject(r"\begin{bmatrix}2&0&0&0&-1&0\\0&2&-2&-2&-1&0\\0&0&1&1&-1&1\\0&0&0&1&5&-5\end{bmatrix}").scale(0.8).set_color(Lime)
        text18 = TextMobject("经观察，矩阵的秩$r(B)=4$").to_edge(DOWN)
        tex20 =TexMobject(r"r(B)=4").shift(DOWN*2+LEFT*3)
        text19 = TextMobject("比涉及物质数量少2").to_edge(DOWN)
        tex21 = TexMobject(r"<n-1").next_to(tex20,RIGHT).set_color(RED).shift(UP*0.1)
        tex22 = TexMobject(r"\Rightarrow \text{有两个线性无关的解向量}").next_to(tex21,RIGHT)
        text23 = TextMobject("根据线性代数理论，可得方程有两个线性无关的解向量").to_edge(DOWN)
        text24 = TextMobject("这类方程，需要更多化学条件限制才能确定").to_edge(DOWN)
        text25 = TextMobject(r"$\Rightarrow $需要更多化学条件限制").next_to(tex12,RIGHT).set_color(Lime).shift(UP*0.1)
        tex23 = TexMobject(r"\uppercase\expandafter{\romannumeral3}.r(A)=n").to_corner(UL)
        tex23[0][3:7].set_color(RED)
        tex23[0][9].set_color(Lime_Green)
        tex23_5 = TexMobject(r"r(A)=n?").set_color_by_gradient([Lime,WHITE,ORANGE]).scale(3)
        text26 = TextMobject("是否存在矩阵的秩与涉及物质数量相等的反应呢？").to_edge(DOWN)
        text27 = TextMobject("以高氯酸分解为例，写出方程式和对应矩阵").to_edge(DOWN)
        tex24 = TexMobject(r"HClO_{4}\overset{\underset{\text{高温}}{}}{=}H_{2}O+Cl_{2}").next_to(line1,DOWN)
        tex25 = TexMobject(r"\begin{bmatrix}1&-2&0\\1&0&-1\\4&-1&0\end{bmatrix}").scale(1.5)
        tex26 = TexMobject(r"C=").scale(1.5).next_to(tex25,LEFT)
        text28 = TextMobject("同样对其初等行变换，将其化为行阶梯形矩阵").to_edge(DOWN)
        tex27 = TexMobject(r"\begin{bmatrix}1&0&-1\\0&1&-4\\0&0&1\end{bmatrix}").scale(1.5).set_color(Lime)
        text29 = TextMobject("经观察，矩阵的秩$r(C)=3$").to_edge(DOWN)
        tex28 =TexMobject(r"r(C)=3").shift(DOWN*2+LEFT*3)
        text30 = TextMobject("与涉及物质数量相同").to_edge(DOWN)
        tex29 = TexMobject(r"=n").next_to(tex28,RIGHT).set_color(RED)
        tex30 = TexMobject(r"\Rightarrow \text{只存在零解} ").next_to(tex29,RIGHT)
        tex31 = TexMobject(r"\Rightarrow \text{反应不存在}").next_to(tex23,RIGHT).shift(UP*0.1).set_color(Lime)
        text31 = TextMobject("根据线性代数理论，可得方程只有零解").to_edge(DOWN)
        text32 = TextMobject("这说明，所写方程式对应反应不存在").to_edge(DOWN)
        text33 = TextMobject("总结").to_corner(UL).set_color(CYAN)
        text34 = TextMobject("1.当$r(A)=n-1$时，方程只存在一个解向量，配平系数选择整数且互素的解").scale(0.7).set_color(Light_YELLOW).to_edge(LEFT).shift(UP)
        text35 = TextMobject("2.当$r(A)<n-1$时，方程存在多个线性无关的解向量，需要更多的化学条件来限制").scale(0.7).set_color(Crimson).next_to(text34,DOWN).to_edge(LEFT)
        text36 = TextMobject("2.1.一般来说，基础解系无关解的数量$=n-r(A)$").scale(0.7).set_color(Lime).next_to(text35,DOWN).to_edge(LEFT)
        text37 = TextMobject("3.当$r(A)=n$时，方程只存在零解，方程式对应反应不存在").scale(0.7).set_color(CYAN).next_to(text36,DOWN).to_edge(LEFT)
        textA = VGroup(text34,text35,text36,text37).scale(0.9)

        self.play(FadeInFrom(text1,DOWN))
        self.wait(1)
        self.play(FadeOut(text1))
        self.wait(1)
        self.play(Write(text2))
        self.play(Write(tex1))
        self.wait(2)
        self.play(ReplacementTransform(text2,text3))
        self.play(Write(tex2))
        self.wait(2)
        self.play(ReplacementTransform(text3,text4))
        self.play(Write(vec1))
        self.play(Write(tex3))
        self.wait(2)
        self.play(FadeOut(tex1),FadeOut(tex2),FadeOut(tex3),FadeOut(vec1))
        self.play(ReplacementTransform(text4,text5))
        self.play(Write(tex4))
        self.wait(2)
        self.play(ReplacementTransform(text5,text6))
        self.play(Write(text7))
        self.wait(2)
        self.play(FadeOut(tex4),FadeOut(text7))
        self.play(ReplacementTransform(text6,text8))
        self.play(Write(line1))
        self.play(Write(tex5))
        self.play(Write(text9))
        self.wait(2)
        self.play(ReplacementTransform(text8,text10))
        self.play(Write(tex6))
        self.play(Write(tex6_5))
        self.play(Write(tex7))
        self.wait(2)
        self.play(ReplacementTransform(text10,text11))
        self.wait(0.5)
        self.play(ReplacementTransform(tex7,tex8))
        self.wait(2)
        self.play(ReplacementTransform(text11,text12))
        self.play(Write(re1),Write(re2))
        self.play(Write(tex9))
        self.wait(2)
        self.play(ReplacementTransform(text12,text13))
        self.play(Write(tex10))
        self.wait(2)
        self.play(ReplacementTransform(text13,text14))
        self.play(Write(tex11))
        self.wait(2.5)
        self.play(Uncreate(tex6),Uncreate(tex6_5),Uncreate(tex8),Uncreate(re1),Uncreate(re2),Uncreate(tex9),Uncreate(tex10),Uncreate(tex11),
        Uncreate(text9))
        self.play(ReplacementTransform(tex5,tex12))
        self.play(ReplacementTransform(text14,text15))
        self.wait(2)
        self.play(ReplacementTransform(text15,text16))
        self.play(Write(tex16_5))
        self.wait(0.5)
        self.play(Write(tex18))
        self.play(Write(tex17))
        self.wait(2)
        self.play(ReplacementTransform(text16,text17))
        self.play(ReplacementTransform(tex17,tex19))
        self.wait(1)
        self.play(ReplacementTransform(text17,text18))
        self.play(Write(tex20))
        self.wait(1.5)
        self.play(ReplacementTransform(text18,text19))
        self.play(Write(tex21))
        self.wait(1.5)
        self.play(ReplacementTransform(text19,text23))
        self.play(Write(tex22))
        self.wait(1.5)
        self.play(ReplacementTransform(text23,text24))
        self.play(Write(text25))
        self.wait(1.5)
        self.play(Uncreate(tex22),Uncreate(tex21),Uncreate(tex20),Uncreate(tex19),Uncreate(tex18),Uncreate(tex16_5),Uncreate(text25))
        self.wait(1.5)
        self.play(ReplacementTransform(tex12,tex23))
        self.play(ReplacementTransform(text24,text26),Write(tex23_5))
        self.wait(1.5)
        self.play(FadeOut(tex23_5))
        self.play(ReplacementTransform(text26,text27))
        self.play(Write(tex24))
        self.play(Write(tex26))
        self.play(Write(tex25))
        self.wait(1.5)
        self.play(ReplacementTransform(text27,text28))
        self.play(ReplacementTransform(tex25,tex27))
        self.wait(1.5)
        self.play(ReplacementTransform(text28,text29))
        self.play(Write(tex28))
        self.wait(1.5)
        self.play(ReplacementTransform(text29,text30))
        self.play(Write(tex29))
        self.wait(1.5)
        self.play(ReplacementTransform(text30,text31))
        self.play(Write(tex30))
        self.wait(1.5)
        self.play(ReplacementTransform(text31,text32))
        self.play(Write(tex31))
        self.wait(1.5)
        self.wait(2)
        self.play(Uncreate(text32),Uncreate(text31),Uncreate(tex31),Uncreate(tex30),Uncreate(tex29),Uncreate(tex28),Uncreate(tex27),Uncreate(tex26),Uncreate(tex24),Uncreate(tex23))
        self.wait(2)
        self.play(Write(text33))
        self.wait(1)
        self.play(Write(text34))
        self.wait(2)
        self.play(Write(text35))
        self.wait(2)
        self.play(Write(text36))
        self.wait(2)
        self.play(Write(text37))
        self.wait(3)
        self.play(FadeOut(textA),FadeOut(line1),FadeOut(text33),run_time=3)

class ckwx(Scene):
    def construct(self):
        text1 = TextMobject("参考资料：").to_corner(UL)
        text2 = TextMobject(r"[1]殷福珊, 刘文华. 配平化学方程式的矩阵变换方法[J]. 化学通报, 1987(06):55-57.").shift(UP*2).to_edge(LEFT)
        text3 = TextMobject("[2]孙会霞, 职桂珍. 线性方程组的基本理论在配平化学方程式中的应用——改进的线性代数法").next_to(text2,DOWN).to_edge(LEFT)
        text8 = TextMobject("[J]. 郑州轻工业学院学报, 2001, 16(4):4.").next_to(text3,DOWN).to_edge(LEFT)
        text4 = TextMobject(r"[3]彭声羽. 线性代数应用于化学方程式[J]. 九江学院学报:社会科学版, 1986(5):75-81.").next_to(text8,DOWN).to_edge(LEFT)
        text5 = TextMobject(r"[4]同济大学数学系.工程数学.线性代数[M].北京：高等教育出版社,2014").next_to(text4,DOWN).to_edge(LEFT)
        text6 = TextMobject(r"[5]曹忠良,王珍云.无机化学反应方程式手册[M].湖南：科学技术出版社,1982").next_to(text5,DOWN).to_edge(LEFT)
        text7 = TextMobject(r"[6]晓之车高山老师.化学方程式居然还可以这么配平?化学老师看懵了!.BV1wL411H7tp,2021").next_to(text6,DOWN).to_edge(LEFT)
        textA = VGroup(text2,text3,text8,text4,text5,text6,text7).scale(0.6).to_edge(LEFT).shift(UP*1.5)
        text8.shift(RIGHT*0.45)
        img1 = ImageMobject("sanlian",height = 6,invert = False).scale(0.4).to_corner(DL)
        img2 = ImageMobject("sanlian2",height = 6,invert = False).scale(0.4).to_corner(DR)

        self.play(Write(text1))
        self.play(Write(textA))
        self.play(FadeIn(img1),FadeIn(img2))
        self.wait(1)